name: 'CI Action'
description: 'Runs tests and linting for the project'
runs:
  using: 'composite'  # Use composite to run multiple steps
  steps:
    - name: Run tests (and coverage)
      run: pytest --cov=app --cov-report=term-missing --cov-fail-under=90 tests/
      shell: bash

    - name: Run linting
      run: flake8 app/ --count --show-source --statistics
      shell: bash

    - name: Run type checking
      run: mypy app/
      shell: bash