name: 'CI Action'
description: 'Runs tests and linting for the project'
runs:
  using: 'composite'  # Use composite to run multiple steps
  steps:
    - name: Run tests
      run: pytest
      shell: bash

    - name: Run linting
      run: flake8 app/ --count --show-source --statistics
      shell: bash