name: Preprocessing CI/CD

on:
  push:
    branches:
      - main
      - setup_CI
  pull_request:
    branches:
      - main

jobs:
  continuous_integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run CI steps
        uses: ./.github/actions/action-ci 

  continuous_deployment:
    runs-on: ubuntu-latest
    needs: continuous_integration
    env:
      AWS_REGION: ap-southeast-2
      ECR_REPOSITORY: preprocessing
      IMAGE_TAG: latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run CD steps
        uses: ./.github/actions/action-cd
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run unit tests
        run: pytest /Users/abbieworswick/preprocessing/tests
