name: Analytics CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-ci:
    uses: W18BTANGO/ci-cd/.github/workflows/integration.yaml@main

  deploy:
    needs: [run-ci]
    uses:  W18BTANGO/ci-cd/.github/workflows/deploy-prod.yaml@main
    with:
      aws-region: ap-southeast-2                        
      ecr-repository: preprocessing               
      ecs-service: preprocessingService                  
      ecs-cluster: PreprocessingClusterEC2                  
      ecs-task-definition: .aws/ptd1-revision1.json              
      container-name: preprocessing                     
                                                        
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
